packages:
  - apps/*
  - packages/*

catalog:
  '@types/node': ^24
  typescript: 5.9.3

catalogs:
  frontend:
    '@types/react': 19.2.0
    '@types/react-dom': 19.2.0
    lucide-react: 0.522.0
    next: 16.0.1
    next-themes: 0.4.6
    react: 19.2.0
    react-dom: 19.2.0

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@scarf/scarf'
  - bufferutil
  - core-js-pure
  - esbuild
  - sharp
  - unrs-resolver
